### ISSUE TITLE
Error: callback was already called

### ISSUE THREAD

**Issue by spiral2k** [gabek/node-internet-radio#8] opened 2019-01-15 21:16 UTC
when calling internetradio.getStationInfo (like 3-4 time in couple of seconds) i'm getting"callback was already called" and "MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit",  probably from async.parallel

**Comment by gabek** [comment] 2019-01-16 00:05
Hey there!  Could you provide a little snip of code that reproduces this?

I wonder if it's time to refactor some of this code to use async/await and move away from the `async` library.

**Comment by spiral2k** [comment] 2019-01-16 21:51
Hi @gabek i will upload a code to reproduce this maybe tomorrow.

i think you should move away from 'async', there is a way to call all the request and get the valid results in easy way, something like that:

`const results = await Promise.all(promises.map(p => p.catch(e => e)));
const validResults = results.filter(result => !(result instanceof Error));`

BTW
you have the best library (i did try all of them), keep it up!

**Comment by kiukishenkaec** [comment] 2019-07-11 12:31
There was the same problem! How to decide?

**Comment by gabek** [comment] 2019-07-11 18:51
Hey @kiukishenkaec!  Do you have an example you can post if it happening?  I've been thinking it's time to update the code to use async/await instead of the `async` library, I just haven't been very motivated to do it.  If you have an example of the issue maybe I'll spend some time using that as the base to update it and fix the bug in the process.

**Comment by kiukishenkaec** [comment] 2019-07-11 19:15
`setInterval(function() {
	playlist.forEach(function(row, index) {
		internetradio.getStationInfo(row.url, function(error, body) {
			sendRequest({ body: body, alias: row.alias });
		});
	});
}, 10000);`

**Comment by gabek** [comment] 2019-08-12 21:59
In theory, this should be fixed with the removal of the async library that was merged in with https://github.com/gabek/node-internet-radio/issues/9.  Thanks to @dbbring for doing this!  @kiukishenkaec and @spiral2k if you want to pull master and try your integrations against it and report back, hopefully it'll be resolved.  I haven't pushed an updated NPM version yet, but that'll happen shortly after some usage.

**Comment by gabek** [comment] 2020-04-07 04:43
Closing since this should all be resolved.

**Closed by gabek** 2020-04-07 04:43 UTC
